Add UOV
mupq/mupq pull request #118
Opened 2023-10-30 03:23 UTC by mkannwischer

https://github.com/mupq/pqm4/issues/296

This add the UOV implementations from
- https://www.uovsig.org/
- https://github.com/pqov/pqov

The M4 implementation is from
- https://eprint.iacr.org/2023/059
- https://github.com/pqov/pqov-paper

Only ov-Ip fits within 640 KB of RAM: 
- ov-Is requires 412160 bytes pk + 348704 bytes sk
- ov-III requires over 2 MB pk + sk
- ov-V requires over 5 MB pk + sk

Note that ov-Is does have an M4 implementation, but it is storing keys in flash which is not supported by mupq/pqm4.

Two comments: 
 - UOV requires a non-standard API for AES in counter mode (it needs to take the initial counter value as an argument). I don't want to modify the API as it would require changing it in PQClean and probably OQS as well and I am not sure how welcome that would be. For now I have added a local implementation. We still want to benefit from the optimized M4 implementation, so we switch between assembly and the reference implementation depending on a flag defining if it is compiled for the host or the M4. Not very pretty. 
 - Our current tests have a failure test case where it generates two key pairs, signs with one, and tries to veify with the other which should fail. This reuires to store two public keys on the stack which won't work for schemes with very big public keys (like classic OV). I added the option to switch to a low-RAM variant which instead of generating two key pairs, only generates one and sets the public key to random bytes before verifying. This variant is behind a flag "BIG_PUBLIC_KEY_TESTS" which has to be set to the config.mk of the respective schemes.

2023-11-02 10:46 UTC, rpls requested changes

2023-11-03 06:05 UTC, mkannwischer commented on crypto_sign/ov-Ip/ref/utils_prng.c
No, AES is not actually round reduced in this version. I have not included the 4-round AES variant yet. It was really just about the API provided for counter mode. See what I wrote in the PR: 
```
UOV requires a non-standard API for AES in counter mode (it needs to take the initial counter value as an argument). I don't want to modify the API as it would require changing it in PQClean and probably OQS as well and I am not sure how welcome that would be. For now I have added a local implementation. We still want to benefit from the optimized M4 implementation, so we switch between assembly and the reference implementation depending on a flag defining if it is compiled for the host or the M4. Not very pretty.
```
Thinking about it more, I agree that we should avoid custom implementations whenever possible. 

I have re-implemented utils_prng.c using the aes128_ecb functions. That also resolves your comment about the very weird code.
This is much prettier and results in roughly the same performance. Just a few more functions calls into aes functions.

Does this look okay for you now?

2023-11-03 06:19 UTC, mkannwischer commented on crypto_sign/ov-Ip/ref/utils_prng.c
Btw: the stack benchmark problems I had were not for UOV. That was for MAYO.

2023-11-05 20:19 UTC, rpls commented on crypto_sign/ov-Ip/ref/utils_prng.c
Yeah looks good, and works on my side. I'll probably merge this during our next call, we need some syncing since multiple PRs change the `mupq` submodule.

2023-11-07 02:10 UTC, mkannwischer commented
Reposting this comment as otherwise it's hidden in the discussion: 

> Thinking about it more, I agree that we should avoid custom implementations whenever possible.
> I have re-implemented utils_prng.c using the aes128_ecb functions. That also resolves your comment about the very weird code.
> This is much prettier and results in roughly the same performance. Just a few more functions calls into aes functions.

2023-11-07 02:20 UTC, mkannwischer commented
I rebased on top of #122. 
I think this is ready to be reviewed & merged.

2023-11-07 07:17 UTC, rpls approved these changes

2023-11-07 07:23 UTC, merged